apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-configmap
  namespace: osm-system
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush             5
      Daemon            off
      Log_Level         error
      Parsers_File      parser.conf
    [INPUT]
      Name    tail
      Tag     kube.*
      Path    /var/log/containers/osm-controller-*_osm-system_osm-controller-*.log
      Parser  docker
    [FILTER]
      Name    grep
      Match   *
      Exclude message .*[nN]amespace.*
    [OUTPUT]
      Name        azure
      Match       *
      Customer_ID 42b0f26b-f8f7-4aa9-9222-25c68b665e62
      Shared_Key  LtGQ5xGr1w2pQuz0NKsDGV+uJNUUIgfN20tjgkYP+nVo/wzUTMO/pOxYKmkLV4r16r529nlX/FM+ZQfb+e41/g==  
  parser.conf: |-
    [PARSER]
      Name          docker
      Format        json
      Time_Key      time
      Time_Format   %Y-%m-%dT%H:%M:%S.%L
      Time_Keep     On